"""Exact finite presentations; no claim that a carrier is the uncut ground."""
from itertools import product


def _same_nonempty(*vectors):
    if not vectors or not vectors[0]:
        raise ValueError("A presentation must be nonempty")
    if any(len(v) != len(vectors[0]) for v in vectors):
        raise ValueError("Functions must share the declared carrier")


def canonical(values):
    """Rename a partition by first occurrence, preserving all equalities."""
    _same_nonempty(values)
    labels = {}
    return tuple(labels.setdefault(v, len(labels)) for v in values)


def partitions(n):
    """All set partitions of n labels, once each (restricted growth words)."""
    if n < 1:
        raise ValueError("n must be positive")

    def extend(prefix):
        if len(prefix) == n:
            yield prefix
        else:
            for label in range(max(prefix) + 2):
                yield from extend(prefix + (label,))

    yield from extend((0,))


def fibres(cut):
    _same_nonempty(cut)
    result = {}
    for x, a in enumerate(cut):
        result.setdefault(a, []).append(x)
    return result


def factor_map(cut, target):
    """The unique decoder on the actual image, or None if it cannot exist."""
    _same_nonempty(cut, target)
    decoder = {}
    for a, v in zip(cut, target):
        if a in decoder and decoder[a] != v:
            return None
        decoder[a] = v
    return decoder


def refines(fine, coarse):
    return factor_map(fine, coarse) is not None


def target_sets(cut, target):
    _same_nonempty(cut, target)
    return {a: frozenset(target[x] for x in block)
            for a, block in fibres(cut).items()}


def repair_size(cut, target):
    return max(map(len, target_sets(cut, target).values()))


def repair_channel(cut, target):
    """Existence construction; a physical device must still realize this map."""
    _same_nonempty(cut, target)
    dictionaries = {}
    labels = []
    for a, v in zip(cut, target):
        local = dictionaries.setdefault(a, {})
        labels.append(local.setdefault(v, len(local)))
    return tuple(labels)


def fixed_binary_bits(alphabet_size):
    if alphabet_size < 1:
        raise ValueError("A nonempty presentation needs a nonempty alphabet")
    return (alphabet_size - 1).bit_length()


def _transition(cut, transition):
    _same_nonempty(cut, transition)
    if any(type(x) is not int or x < 0 or x >= len(cut) for x in transition):
        raise ValueError("Transition must be a total endomap of the carrier")


def descended_transition(cut, transition):
    _transition(cut, transition)
    return factor_map(cut, tuple(cut[y] for y in transition))


def stable_history(cut, transition):
    """U6: compute the least closed refinement from finite future signatures."""
    _transition(cut, transition)
    histories = tuple((a,) for a in cut)
    current = canonical(histories)
    positions = tuple(range(len(cut)))
    levels = [current]
    for _ in range(len(cut)):
        positions = tuple(transition[x] for x in positions)
        extended = tuple(h + (cut[y],) for h, y in zip(histories, positions))
        following = canonical(extended)
        if following == current:
            return {"cut": current, "depth": len(levels) - 1,
                    "levels": tuple(levels),
                    "transition": descended_transition(current, transition)}
        current, histories = following, extended
        levels.append(current)
    raise RuntimeError("Finite partition refinement failed to stabilize")


def joint_fibre(cuts, readouts):
    if not cuts or len(cuts) != len(readouts):
        raise ValueError("Supply one readout per cut")
    _same_nonempty(*cuts)
    return tuple(x for x in range(len(cuts[0]))
                 if all(cut[x] == a for cut, a in zip(cuts, readouts)))


def common_components(cuts):
    """Connected components generated by the union of fibre equalities."""
    _same_nonempty(*cuts)
    parent = list(range(len(cuts[0])))

    def root(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for cut in cuts:
        for block in fibres(cut).values():
            for x in block[1:]:
                parent[root(x)] = root(block[0])
    return canonical(tuple(root(x) for x in range(len(parent))))


def all_endomaps(n):
    if n < 1:
        raise ValueError("n must be positive")
    return product(range(n), repeat=n)
